#pragma once

enum class CollisionTypeEnum {
	BEGIN,
	NO_COLLISION = BEGIN,
	PLAYER_ENEMY_COLLISION,
	PLAYER_PROJECTILE_COLLISION,
	ENEMY_PROJECTILE_COLLISION,
	PLAYER_VEGETATION_COLLIDER,
	PLAYER_LEVEL_COMPLETE_COLLISION,
	END = PLAYER_LEVEL_COMPLETE_COLLISION
};